from triage.basic_triage import calculate_priority


def run_adri(location_data, vrp_routes):
    """
    ADRI V1 backend pipeline.

    location_data:
        List of disaster locations containing perception outputs.

    vrp_routes:
        Routes generated by the basic VRP module.
    """

    triage_results = []

    # Step 1: Run triage for every location
    for location in location_data:

        result = calculate_priority(location)

        triage_results.append(result)

    # Step 2: Prepare final backend response
    response = {
        "locations": triage_results,
        "routes": vrp_routes
    }

    return response


# ------------------------------------------------
# V1 TEST DATA
# ------------------------------------------------

if __name__ == "__main__":

    locations = [

        {
            "location_id": "A1",

            "victims": {
                "count": 8
            },

            "infrastructure": {
                "damage_score": 0.80
            },

            "road": {
                "accessibility": 0.30
            },

            "survivor_likelihood": 0.90
        },

        {
            "location_id": "A2",

            "victims": {
                "count": 3
            },

            "infrastructure": {
                "damage_score": 0.40
            },

            "road": {
                "accessibility": 0.80
            },

            "survivor_likelihood": 0.60
        }
    ]

    # Temporary V1 VRP result.
    # Later this will come directly from basic_vrp.py.
    routes = [
        {
            "vehicle_id": 0,
            "route": ["DEPOT", "A1", "A2", "DEPOT"]
        }
    ]

    result = run_adri(locations, routes)

    print("\n===== ADRI V1 BACKEND =====\n")

    for location in result["locations"]:
        print(
            f"{location['location_id']} → "
            f"{location['priority']} "
            f"({location['priority_score']})"
        )

    print("\nRoutes:")

    for route in result["routes"]:
        print(
            f"Vehicle {route['vehicle_id']}: "
            f"{' → '.join(route['route'])}"
        )
